### ISSUE TITLE
[REQUEST Membership]: New membership for ZiMengSheng

### ISSUE THREAD

**Issue by ZiMengSheng** [koordinator-sh/community#1]
## GitHub Username

ZiMengSheng

## Github Organization you are requesting membership in

koordinator-sh

## Sponsors

@eahydra
@FillZpp 

## Requirements

- [X] I have joined in the community *Slack* or *DingTalk*
- [X] I often attend Koordinator Community Week
- [X] I have reviewed the [membership] docs
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have fixed my affiliation in [cncf/gitdm])
- [X] I am actively contributing to 1 or more Koordinator subprojects

## List of your contributions 
- PRs reviewed / authored: https://github.com/koordinator-sh/koordinator/pulls?q=involves%3AZiMengSheng+
- Issues : https://github.com/koordinator-sh/koordinator/issues?q=involves%3AZiMengSheng

[membership]: https://github.com/koordinator-sh/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by eahydra** [comment]
Welcome!  🚀🚀🚀 🎉🎉🎉

**Comment by FillZpp** [comment]
+1 Welcome! 👍

**Comment by FillZpp** [comment]
@ZiMengSheng Congratulations! 🎉

Remember to change your organization visibility to public. https://github.com/orgs/koordinator-sh/people

/close
