### ISSUE TITLE
[REQUEST Membership]: New membership for xigang

### ISSUE THREAD

**Issue by xigang** [koordinator-sh/community#2]
## GitHub Username
xigang

## Github Organization you are requesting membership in
koordinator-sh

## Sponsors
@FillZpp  @jasonliu747 @eahydra

## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [x] I often attend Koordinator Community Week
- [x] I have reviewed the [membership] docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have fixed my affiliation in [cncf/gitdm])
- [x] I am actively contributing to 1 or more Koordinator subprojects

## List of your contributions 
- PRs reviewed / authored:
- https://github.com/koordinator-sh/koordinator/pull/1158
- https://github.com/koordinator-sh/koordinator/pull/1169
- https://github.com/koordinator-sh/koordinator/pull/1180
- https://github.com/koordinator-sh/koordinator/pull/1208
- https://github.com/koordinator-sh/koordinator/pull/1209
- https://github.com/koordinator-sh/koordinator/pull/1212

[membership]: https://github.com/koordinator-sh/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by jasonliu747** [comment]
@xigang Hi, I noticed that you have submitted a lot of Pull Requests in these few days. Thank you very much for your contribution to our Koordinator community. I am also happy to receive your membership application submission.

Before becoming a member, could you try to solve one or more issues from our issue list? There are still many issues waiting for developers to resolve in our issue list. The address of the issue list is https://github.com/koordinator-sh/koordinator/issues.

By contributing to the resolution of issues on our repository, you will demonstrate your skills and interest in our project. It will also give us a better idea of your ability to work with our team.

If you are new to open-source projects or not familiar with GitHub, don't worry. We are happy to provide guidance and support to help you get started.

Once you feel confident in your ability to contribute to our project, we are happy to have you on board. We look forward to seeing your contributions and working with you!

**Comment by xigang** [comment]
> @xigang Hi, I noticed that you have submitted a lot of Pull Requests in these few days. Thank you very much for your contribution to our Koordinator community. I am also happy to receive your membership application submission.
> 
> Before becoming a member, could you try to solve one or more issues from our issue list? There are still many issues waiting for developers to resolve in our issue list. The address of the issue list is https://github.com/koordinator-sh/koordinator/issues.
> 
> By contributing to the resolution of issues on our repository, you will demonstrate your skills and interest in our project. It will also give us a better idea of your ability to work with our team.
> 
> If you are new to open-source projects or not familiar with GitHub, don't worry. We are happy to provide guidance and support to help you get started.
> 
> Once you feel confident in your ability to contribute to our project, we are happy to have you on board. We look forward to seeing your contributions and working with you!

@jasonliu747 okay, I close this member request first.
