### ISSUE TITLE
[REQUEST Membership]: New membership for baowj-678

### ISSUE THREAD

**Issue by baowj-678** [koordinator-sh/community#5]
## GitHub Username
@baowj-678

## Github Organization you are requesting membership in

koordinator-sh

## Sponsors

@eahydra
@FillZpp

## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [x] I often attend Koordinator Community Week 
- [x] I have reviewed the [membership](https://github.com/koordinator-sh/community/blob/master/community-membership.md) docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have fixed my affiliation in [cncf/gitdm](https://github.com/cncf/gitdm#addingupdating-affiliation))
- [x] I am actively contributing to 1 or more Koordinator subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/koordinator-sh/koordinator/pull/1454
https://github.com/koordinator-sh/koordinator/pull/1571
https://github.com/koordinator-sh/koordinator/pull/1586
https://github.com/koordinator-sh/koordinator/pull/1625
https://github.com/koordinator-sh/koordinator/pull/1651

- Issues :
https://github.com/koordinator-sh/koordinator/issues/1644

**Comment by eahydra** [comment]
Welcome!

**Comment by FillZpp** [comment]
+1 Welcome!

**Comment by FillZpp** [comment]
@baowj-678 I have invited you to our organization, please check your email box, and remember to change your organization visibility to public. https://github.com/orgs/koordinator-sh/people

/close

**Comment by jasonliu747** [comment]
Welcome!
