### ISSUE TITLE
[REQUEST Membership]: New membership for <xulinfei1996>

### ISSUE THREAD

**Issue by xulinfei1996** [koordinator-sh/community#6]
## GitHub Username

@xulinfei1996
## Github Organization you are requesting membership in

koordinator-sh

## Sponsors

@eahydra 
@buptcozy
## Requirements

- [x] I have joined in the community *Slack* or *DingTalk*
- [x] I often attend Koordinator Community Week
- [x] I have reviewed the [membership] docs
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [x] I have fixed my affiliation in [cncf/gitdm])
- [x] I am actively contributing to 1 or more Koordinator subprojects

## List of your contributions 
- PRs reviewed / authored:
https://github.com/koordinator-sh/koordinator/pull/515
https://github.com/koordinator-sh/koordinator/pull/541
https://github.com/koordinator-sh/koordinator/pull/584
https://github.com/koordinator-sh/koordinator/pull/585
https://github.com/koordinator-sh/koordinator/pull/660
https://github.com/koordinator-sh/koordinator/pull/675
https://github.com/koordinator-sh/koordinator/pull/681
https://github.com/koordinator-sh/koordinator/pull/704
https://github.com/koordinator-sh/koordinator/pull/764
https://github.com/koordinator-sh/koordinator/pull/821
https://github.com/koordinator-sh/koordinator/pull/1380
https://github.com/koordinator-sh/koordinator/pull/1553
https://github.com/koordinator-sh/koordinator/pull/1566
https://github.com/koordinator-sh/koordinator/pull/1755
https://github.com/koordinator-sh/koordinator/pull/1839
https://github.com/koordinator-sh/koordinator/pull/1879
https://github.com/koordinator-sh/koordinator/pull/1887
- Issues :
https://github.com/koordinator-sh/koordinator/issues/1379

[membership]: https://github.com/koordinator-sh/community/blob/master/community-membership.md
[cncf/gitdm]: https://github.com/cncf/gitdm#addingupdating-affiliation

**Comment by eahydra** [comment]
Awesome!  Welcome!  🎉🎉🎉

**Comment by eahydra** [comment]
cc @hormes
